export const CALCULATOR_SERVICE = 'CALCULATOR_SERVICE';
export const EXPRESSION_COUNTER_SERVICE = 'EXPRESSION_COUNTER_SERVICE';
export const REGEXP_CREATOR_SERVICE_INTERFACE =
  'REGEXP_CREATOR_SERVICE_INTERFACE';
